# Generated by Django 3.1.7 on 2021-04-30 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloudoverview', '0002_auto_20210428_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialcloud',
            name='cloud_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='cpu_contention',
            field=models.FloatField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='number_of_hosts',
            field=models.IntegerField(blank=True, default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='provisioning',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='ram_contention',
            field=models.FloatField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='storage',
            field=models.FloatField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='total_cpu',
            field=models.FloatField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='total_ram',
            field=models.FloatField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='version',
            field=models.CharField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
    ]
