# Generated by Django 3.1.7 on 2021-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudoverview', '0004_auto_20210430_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialcloud',
            name='number_of_hosts',
            field=models.IntegerField(blank=True, max_length=32),
        ),
    ]
