# Generated by Django 3.1.7 on 2021-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudoverview', '0007_auto_20210430_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialcloud',
            name='cpu_contention',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='ram_contention',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='storage',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='total_cpu',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='potentialcloud',
            name='total_ram',
            field=models.FloatField(max_length=32),
        ),
    ]
