# Generated by Django 3.1.7 on 2021-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderableItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cpu', models.CharField(blank=True, max_length=32, null=True)),
                ('total_ram', models.CharField(blank=True, max_length=32, null=True, verbose_name='Total RAM (MB):')),
                ('total_volume_storage', models.CharField(blank=True, max_length=32, null=True, verbose_name='Total Volume Storage (GB):')),
                ('worker_count', models.CharField(blank=True, max_length=32, null=True)),
                ('worker_cpu', models.CharField(blank=True, max_length=32, null=True)),
                ('worker_ram', models.CharField(blank=True, max_length=32, null=True)),
                ('director_count', models.CharField(blank=True, max_length=32, null=True)),
                ('director_cpu', models.CharField(blank=True, max_length=32, null=True)),
                ('director_ram', models.CharField(blank=True, max_length=32, null=True)),
                ('master_count', models.CharField(blank=True, max_length=32, null=True)),
                ('master_cpu', models.CharField(blank=True, max_length=32, null=True)),
                ('master_ram', models.CharField(blank=True, max_length=32, null=True)),
                ('volume_quota', models.CharField(blank=True, max_length=32, null=True)),
                ('ecfe_ip_count', models.CharField(blank=True, max_length=32, null=True)),
                ('static_ip_count', models.CharField(blank=True, max_length=32, null=True)),
                ('nfs_required', models.BooleanField(default=False)),
                ('workers_affinity_rule', models.BooleanField(default=False)),
            ],
        ),
    ]
