# Generated by Django 3.1.7 on 2021-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderableitems',
            old_name='director_count',
            new_name='director_node_count',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='director_cpu',
            new_name='director_vcpu',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='master_count',
            new_name='master_node_count',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='master_cpu',
            new_name='master_vcpu',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='total_cpu',
            new_name='nfs_server_node_count',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='volume_quota',
            new_name='nfs_server_ram',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='worker_count',
            new_name='nfs_server_vcpu',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='worker_cpu',
            new_name='orderable_item_name',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='worker_ram',
            new_name='total_node_count',
        ),
        migrations.RenameField(
            model_name='orderableitems',
            old_name='total_volume_storage',
            new_name='volume_storage',
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='ram',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Total RAM (MB):'),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='total_vcpu',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='total_vm_count',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='vcpu',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='worker_app_node_count',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='worker_app_ram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='worker_app_vcpu',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='worker_net_node_count',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='worker_net_ram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitems',
            name='worker_net_vcpu',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='orderableitems',
            name='total_ram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
