# Generated by Django 3.1.7 on 2021-04-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0002_auto_20210406_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderableItems',
            new_name='OrderableItem',
        ),
    ]
