# Generated by Django 3.1.7 on 2021-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0004_auto_20210406_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('number_of_hosts', models.CharField(blank=True, max_length=32, null=True)),
                ('physical_cpu_host', models.CharField(blank=True, max_length=32, null=True)),
                ('cpu_contention', models.CharField(blank=True, max_length=32, null=True)),
                ('ram_per_host', models.CharField(blank=True, max_length=32, null=True)),
                ('ram_contention', models.CharField(blank=True, max_length=32, null=True)),
                ('storage', models.CharField(blank=True, max_length=32, null=True)),
                ('ecfe_ips', models.CharField(blank=True, max_length=32, null=True)),
                ('static_ips', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
