# Generated by Django 3.1.7 on 2021-04-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0005_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='total_cpu',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cloud',
            name='total_ram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
