# Generated by Django 3.1.7 on 2021-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0006_auto_20210407_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderableitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderableitem',
            name='orderable_item_name',
            field=models.CharField(blank=True, default='', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
