# Generated by Django 3.1.7 on 2021-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0007_auto_20210414_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderableitem',
            name='orderable_item_name',
            field=models.CharField(blank=True, default='', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
