# Generated by Django 3.1.7 on 2021-04-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0008_auto_20210415_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderableitem',
            name='cENM_client_node_count',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='cENM_client_ram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='cENM_client_vcpu',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
