# Generated by Django 3.1.7 on 2021-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0009_auto_20210416_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderableitem',
            name='ram',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Total RAM (GB):'),
        ),
    ]
