# Generated by Django 3.1.7 on 2021-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0010_auto_20210716_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderableitem',
            name='self_managed',
            field=models.BooleanField(default=False),
        ),
    ]
