# Generated by Django 3.1.7 on 2022-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceaccommodator', '0011_orderableitem_self_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderableitem',
            name='container_registry_storage_size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='director_config_volume_size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='director_flavor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='director_root_volume_size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='master_flavor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='master_root_config_volume_size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='master_root_volume_size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='worker_flavor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderableitem',
            name='worker_root_volume_size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
